FROM node:16 AS dev

COPY ./app /nmos-crosspoint/app
COPY ./server /nmos-crosspoint/server

ENV PATH /nmos-crosspoint/server/node_modules/.bin:$PATH
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /nmos-crosspoint/app
RUN npm install --force

WORKDIR /nmos-crosspoint/server
RUN npm install -g typescript@latest
RUN npm install -g tsc-watch@latest
RUN npm install

CMD cd /nmos-crosspoint/server && npm run debug & cd /nmos-crosspoint/app && npm run start