FROM node:20 AS dev

COPY ./ui /nmos-crosspoint/ui
COPY ./server /nmos-crosspoint/server
ENV PATH /nmos-crosspoint/server/node_modules/.bin:$PATH
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /nmos-crosspoint/ui
RUN npm install
RUN npm run build

WORKDIR /nmos-crosspoint/server
RUN npm install -g typescript@latest
RUN npm install -g tsc-watch@latest
RUN npm install

CMD cd /nmos-crosspoint/server && npm run dev & cd /nmos-crosspoint/ui && npm run dev